---
image: qbittorrent
version: v0.2.6
name: qBittorrent
description: "The [Qbittorrent](https://www.qbittorrent.org/) project aims to provide an open-source software alternative to ÂµTorrent. qBittorrent is based on the Qt toolkit and libtorrent-rasterbar library."
ext_release: v2.6.0
arch:
  - aarch64
  - x86_64
